apiVersion: v1
kind: Pod
metadata:
  name: mosquitto-manager
  labels:
    name: mosquitto-manager
spec:
  shareProcessNamespace: true
  containers:
    - name: mosquitto-basic
      image: passarinho/mosquitto-basic
      imagePullPolicy: Always
    - name: mosquitto-manager
      image: passarinho/mosquitto-manager
      imagePullPolicy: Always
      args: ["-acl=false", "--mongoUri=mongodb://10.77.129.131:27017/"]
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE

